const lang = {
    ar : {
        FORCLIENTS : "للعملاء",
        Findtalentyourway:"ابحث عن المواهب على طريقتك",
        Developtrustedrelationships:"طوّر علاقات موثوقة وقم ببناء منصة المواهب الافتراضية الخاصة بك لإجراء تحولات سريعة للمشروع أو التحولات الكبيرة.",
        Postajobandhireapro: "انشر وظيفة وظّف محترفًا",
        TalentMarketplace : "سوق المواهب",
        Browseandbuyprojects:"تصفح وشراء المشاريع",
        ProjectCatalog:"كتالوج المشروع",
        Letusfindtherighttalent : "دعونا نجد الموهبة المناسبة",
        TalentScout:"المواهب الكشفية",
        Needasolutionforlargeorganizations:"هل تحتاج إلى حل للمنظمات الكبيرة؟",
        EnterpriseSuitehasyoucovered : "جناح المؤسسة قد غطيت.",
        DevelopmentIT:"التطوير وتكنولوجيا المعلومات",
        DesignCreative:"التصميم والإبداع",
        SalesMarketing: "المبيعات والتسويق",
        Writing : " الكتابة",
        CustomerSupport:"دعم العملاء",
        Accounting : "محاسبة",
        Seeallcatrgories:"مشاهدة كل الفئات",
        ARVRDevelopment:"AR / VR التنمية",
        AutomationTesting : "اختبار الأتمتة",
        BackEndDevelopment:"تطوير النهاية الخلفية",
        BusinessApplicationsDevelopment : "تطوير تطبيقات الأعمال",
        CMSDevelopment:"تطوير CMS",
        CloudEngineering:"الهندسة السحابية",
        CodingTutoring: "دروس الترميز",
        DatabaseAdministration : "إدارة قواعد البيانات",
    },
    en : {
        FORCLIENTS : "FOR CLIENTS",
        Findtalentyourway:"Find talent your way",
        Developtrustedrelationships:" Develop trusted relationships and build your own virtual talent bench for quick project turnarounds or big transformations.",
        Postajobandhireapro: "Post a job and hire a pro",
        TalentMarketplace : "Talent Marketplace",
        Browseandbuyprojects:"Browse and buy projects",
        ProjectCatalog:"Project Catalog",
        Letusfindtherighttalent : "Let us find the right talent",
        TalentScout:"Talent Scout",
        Needasolutionforlargeorganizations:"Need a solution for large organizations?",
        EnterpriseSuitehasyoucovered : "Enterprise Suite has you covered.",
        DevelopmentIT:"Development & IT",
        DesignCreative:"Design & Creative",
        SalesMarketing: "Sales & Marketing",
        Writing : "Writing",
        CustomerSupport:"Customer Support",
        Accounting : "Accounting",
        Seeallcatrgories:"See all catrgories",
        ARVRDevelopment:"AR/VR Development",
        AutomationTesting : "Automation Testing",
        BackEndDevelopment:"Back-End Development",
        BusinessApplicationsDevelopment : "Business Applications Development",
        CMSDevelopment:"CMS Development",
        CloudEngineering:"Cloud Engineering",
        CodingTutoring: "Coding Tutoring",
        DatabaseAdministration : "Database Administration",
    }
};
export default lang;