import React, { useState } from "react";
import CustomButtonwithbackground from "../../TalentComponents/CustomButtonwithBackground/CustomButton";
import CustomButtonwithoutbackground from "./../../../Components/TalentComponents/CustomButtonwithoutbackground/CustomButton";
import DropDownList from "./../../TalentComponents/DropDownList Component/dropdown";
export default function Verification() {
  const [dropdown, setDropdown] = useState({
    label: " choose the question ",
    names: [
      "your best friend's name",
      "your favorite sports team ",
      "your favorite writer",
      "your mother's maiden name",
      "your first Pets name",
      "the name of elementary school",
    ],
  });
  return (
    <>
      <style
        dangerouslySetInnerHTML={{
          __html:
            "\n    @import url(//db.onlinewebfonts.com/c/3def92f7b2ad644bd382798ecc8ca4c7?family=Canela);\n     {\n        .container {\n             ;\n        }\n    }\n\n    * {\n        margin: 0;\n        padding: 0;\n        \n\n    }\n    body{\n        ;\n\n    }\n",
        }}
      />

      <div className="container card mt-3 mb-3">
        <div className="row mt-3">
          <div className="col-md-6">
            <h5 className=" ps-3 fw-bold">Two-step verification options</h5>
          </div>
          <div className="col-md-6 text-end"></div>
          <small className="ps-3 text-muted">
            Add an extra layer of security to block unauthorized access and
            protect your account.
          </small>
        </div>

        <hr />
        <div className="row mt-3">
          <div className="col-md-6">
            <h5 className=" ps-3 fw-bold ">
              Authenticator app code <small>(Recommended)</small>{" "}
            </h5>
          </div>
          <div className="col-md-6 text-end">
            <CustomButtonwithbackground headers="Enable" />
          </div>
          <small className="ps-3 text-muted">
            Enter a code generated by your authenticator app to confirm it’s
            you.
          </small>
        </div>
        <hr />
        <div className="row">
          <div className="col-md-6">
            <h5 className=" ps-3 fw-bold">Mobile app prompt </h5>
          </div>
          <div className="col-md-6 text-end">
            <CustomButtonwithbackground headers="Enable" />
          </div>
          <small className="ps-3 text-muted">
            Receive a prompt from your mobile app to confirm it’s you.
          </small>
        </div>

        <hr />
        <div className="row">
          <div className="col-md-6">
            <h5 className=" ps-3 fw-bold">Text message </h5>
          </div>
          <div className="col-md-6 text-end">
            <CustomButtonwithbackground headers="Enable" />
          </div>

          <small className="ps-3 text-muted">
            Receive a six digit code by text message to confirm it’s you.
          </small>
        </div>
        <hr />
        <div className="row">
          <div className="col-md-6">
            <h5 className=" ps-3 fw-bold">Authenticator app code </h5>
          </div>
          <div className="col-md-6 d-flex justify-content-end">
            <button
              type="button"
              className="btn btn-default me-2 d-flex justify-content-center border rounded-circle"
              style={{
                width: "30px",
                height: "30px",
                textAlign: "center",
                paddingTop: "3px",
                paddingBottom: "3px",
              }}
              data-bs-toggle="modal"
              data-bs-target="#exampleModal4"
            >
              <div>
                <i className="fas fa-pen"></i>
              </div>
            </button>
          </div>
        </div>
        <small className="ps-3 text-muted">
          Answer a question you choose to confirm it’s you.
        </small>
        <hr />
      </div>

      <div
        className="modal fade"
        id="exampleModal4"
        tabindex="-1"
        aria-labelledby="exampleModalLabel"
        aria-hidden="true"
      >
        <div className="modal-dialog">
          <div className="modal-content">
            <div className="modal-header">
              <h5 className="modal-title" id="exampleModalLabel">
                Security question
              </h5>
              <button
                type="button"
                className="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
            </div>
            <div className="modal-body">
              <form>
                <div className=" mb-3">
                  <label
                    for="exampleFormControlInput1"
                    className="form-label fw-bold"
                  >
                    Before you can set a new security question, you’ll have to
                    answer your current one correctly.
                  </label>
                  <h5 className="mt-3 fw-bold">Current Question</h5>
                  <p>Your best friend's nickname</p>

                  <label
                    for="exampleFormControlInput2"
                    className="form-label fw-bold"
                  >
                    Answer
                  </label>
                  <input
                    type="text"
                    className="form-control mb-3"
                    id="exampleFormControlInput2"
                  />
                  <hr />
                </div>
                <div className=" row mb-3 mt-3">
                  <h5 className="fw-bold"> New Question</h5>
                  <DropDownList dropdowndata={dropdown} />
                </div>
                <label
                  for="exampleFormControlInput3"
                  className="form-label fw-bold"
                >
                  Answer
                </label>
                <input
                  type="text"
                  className="form-control mb-3"
                  id="exampleFormControlInput3"
                />
                <div className="input-group-text mt-2 bg-white">
                  <input
                    className="no-border"
                    type="checkbox"
                    id="flexCheckDefault"
                  />
                  I understand my account will be locked if I am unable to
                  answer this question
                </div>
                <div className="input-group-text mt-2 bg-white">
                  <input
                    className="no-border"
                    type="checkbox"
                    id="flexCheckDefault"
                  />
                  <small className="  ms-2">
                    Keep me logged in on this device
                  </small>
                </div>
              </form>
            </div>
            <div className="modal-footer">
              <CustomButtonwithbackground headers="cancel" />
              <CustomButtonwithoutbackground headers="save" />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
