const lang = {
    ar : {
        WHATTHEYSAY : "ماذا يقولون",
        ThefreelancetalentthatImabletoaccess:"“الموهبة المستقلة التي يمكنني الوصول إليها تخلق إنتاجية بطريقة لا أعتقد أن أيًا منا اعتقد أنها ممكنة.”",
        CaraBedford:"كارا بيدفورد",
        DirectorStrategicMarketing: "مدير التسويق الاستراتيجي ، CompuVision",
        MyrelationshipwithCara : "“نمت علاقتي مع Cara & CompuVision على مر السنين. لقد واصلنا العمل معًا في مشاريع أكبر وأكثر تقنية .”",
        SamCrockett:"سام كروكيت",
        IndependentWebDeveloper:"مطور ويب مستقل",
        REVIEWS:"(352،169 تقييمات)",
        TOPSKILLS:"مهارات عالية",
        DataEntrySpecialists:"متخصصو إدخال البيانات",
        VideoEditors:"محرري الفيديو",
        DataAnalyst:"محلل بيانات",
        ShopifyDeveloper:" مطور شوبيفي",
        RubyonRailsDeveloper:"مطور روبي أون ريلز",
        AndroidDeveloper:" مطور اندرويد",
        Bookkeeper:"محاسب",
        ContentWriter:"كاتب محتوى",
        Copywriter:"مؤلف الإعلانات",
        DatabaseAdministrator:"مسؤول قاعدة البيانات",
        DataScientist:"عالم البيانات",
        FrontEndDeveloper:"مطور الواجهة الأمامية",
        Seemore:"شاهد المزيد",
        Browseall:"تصفح الكل",
    },
    en : {
        WHATTHEYSAY : "WHAT THEY SAY",
        ThefreelancetalentthatImabletoaccess:"“The freelance talent that I’m able to access creates productivity in a way that I don’t think any of us thought possible.”",
        CaraBedford:"Cara Bedford",
        DirectorStrategicMarketing: "Director Strategic Marketing, CompuVision",
        MyrelationshipwithCara : "“My relationship with Cara & CompuVision has grown over the years. We’ve continued to work together on larger and more technical projects.”",
        SamCrockett:"Sam Crockett",
        IndependentWebDeveloper:"Independent Web Developer",
        REVIEWS:"(352,169 REVIEWS)",
        TOPSKILLS:"TOP SKILLS",
        DataEntrySpecialists:"Data Entry Specialists",
        VideoEditors:"Video Editors",
        DataAnalyst:"Data Analyst",
        ShopifyDeveloper:"Shopify Developer",
        RubyonRailsDeveloper:"Ruby on Rails Developer",
        AndroidDeveloper:"Android Developer",
        Bookkeeper:"Bookkeeper",
        ContentWriter:"Content Writer",
        Copywriter:"Copywriter",
        DatabaseAdministrator:"Database Administrator",
        DataScientist:"Data Scientist",
        FrontEndDeveloper:"Front-End Developer",
        Seemore:"See more",
        Browseall:"Browse all",
    }
};
export default lang;